pizzeria/pizzeria/urls.py
"""Defines URL patters for Pizzeria"""

from django.urls import path

from . import views

app_name = "pizzeria"
urlpatterns = [
    # Home page
    path("", views.index, name="index"),
    path("pizzas", views.pizzas, name="pizzas"),
    path("pizza/<int:pizza_id>", views.pizza, name="pizza"),
]

pizzeria/pizzeria_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("pizzeria.urls")),
]

pizzeria/pizzeria/models.py
from django.db import models


class Pizza(models.Model):
    """A type of pizza."""

    name = models.CharField(max_length=50)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Return the name of the pizza."""
        return self.name.title()


class Topping(models.Model):
    """A specific topping for the pizza."""

    name = models.CharField(max_length=50)
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)

    def __str__(self):
        """Returns the name of the topping."""
        return self.name

pizzeria/pizzeria/views.py
from django.shortcuts import render
from .models import Pizza


def index(request):
    """The home page for pizzeria."""
    return render(request, "pizzeria/index.html")


def pizzas(request):
    """Page to list all pizzas."""
    pizzas = Pizza.objects.order_by("name")
    context = {"pizzas": pizzas}
    return render(request, "pizzeria/pizzas.html", context)


def pizza(request, pizza_id):
    """Detail page for single pizza"""
    pizza = Pizza.objects.get(id=pizza_id)
    toppings = pizza.topping_set.order_by("name")
    context = {"pizza": pizza, "toppings": toppings}
    return render(request, "pizzeria/pizza.html", context)

pizzeria/pizzeria/templates/pizzeria/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Pizzeria!</title>
  </head>
  <body>
    {% block content %} {% endblock content %}
  </body>
</html>

pizzeria/pizzeria/templates/pizzeria/index.html
{% extends 'pizzeria/base.html' %} {% block content %}

<a href="{% url 'pizzeria:index' %}">Home</a> -
<a href="{% url 'pizzeria:pizzas' %}">Pizzas</a> -

<h1>Pizzeria!!!</h1>

<p>home page for pizzeria</p>

{% endblock content %}

pizzeria/pizzeria/templates/pizzeria/pizza.html
{% extends 'pizzeria/base.html' %} {% block content %}

<h1>{{ pizza.name }}</h1>
<h3>Toppings:</h3>
<ul>
  {% for topping in toppings %}
  <li>
    <p>{{topping}}</p>
  </li>
  {% empty %}
  <li><p>No toppings on this pizza!</p></li>
  {% endfor %}
</ul>

{% endblock content%}

pizzeria/pizzeria/templates/pizzeria/pizzas.html
{% extends 'pizzeria/base.html' %} {% block content %}
<h1>Pizzas</h1>

{% for pizza in pizzas %}
<ul>
  <li><a href="{% url 'pizzeria:pizza' pizza.id %}">{{ pizza.name }}</a></li>
</ul>
{% empty %}
<p>No pizzas here!</p>
{% endfor %} {% endblock content %}