blog/Blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("", include("blogs.urls")),
]

blog/accounts/urls.py
"""Defines URL patterns for accounts."""

from django.urls import path, include

from . import views

app_name = "accounts"
urlpatterns = [
    # Include default auth urls.
    path("", include("django.contrib.auth.urls")),
    # Registration page.
    path("register/", views.register, name="register"),
]

blog/blogs/urls.py
"""defines URL patterns for blogs."""

from django.urls import path

from . import views

app_name = "blogs"
urlpatterns = [
    # Home page
    path("", views.index, name="index"),
    # Create a new post
    path("new_post/", views.new_post, name="new_post"),
    # Edit a post
    path("edit_post/<int:post_id>", views.edit_post, name="edit_post"),
]

blog/accounts/models.py
from django.db import models

# Create your models here.

blog/blogs/models.py
from django.db import models
from django.contrib.auth.models import User


class Blog(models.Model):
    """Overall model for blog"""

    text = models.CharField(max_length=200)

    def __str__(self):
        return self.text


class Post(models.Model):
    """A single post."""

    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        """Returns a string representing the blog post."""
        if len(self.title) > 50:
            return f"{self.title[:50]}..."
        else:
            return self.title

blog/blogs/forms.py
from django import forms

from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["title", "text"]
        labels = {"title": "title", "text": "text"}
        widgets = {"text": forms.Textarea(attrs={"cols": 80})}

blog/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm


def register(request):
    if request.method != "POST":
        # Display blank registration form.
        form = UserCreationForm()
    else:
        # POST data received. process data.
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # Log the user in and redirect to home page.
            login(request, new_user)
            return redirect("blogs:index")

    # Display blank or invalid form.
    context = {"form": form}
    return render(request, "registration/register.html", context)

blog/blogs/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404

from .models import Blog, Post
from .forms import PostForm


def index(request):
    """Home page."""
    blog = Blog.objects.get(id=1)
    posts = blog.post_set.order_by("-date_added")
    context = {"posts": posts}
    return render(request, "blogs/index.html", context)


@login_required
def new_post(request):
    """Create a new post"""
    blog = Blog.objects.get(id=1)

    if request.method != "POST":
        # No data submitted, create a blank form.
        form = PostForm()
    else:
        # POST data submitted, process data.
        form = PostForm(data=request.POST)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.blog = blog
            new_post.owner = request.user
            new_post.save()
            return redirect("blogs:index")

    # Display a blank or invalid form.
    context = {"form": form}
    return render(request, "blogs/new_post.html", context)


@login_required
def edit_post(request, post_id):
    """Edit existing post."""
    post = Post.objects.get(id=post_id)
    check_owner_post(post.owner, request.user)

    if request.method != "POST":
        # No data submitted, create form w/ post data.
        form = PostForm(instance=post)
    else:
        # POST data received; process data.
        form = PostForm(instance=post, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect("blogs:index")

    context = {"post": post, "form": form}
    return render(request, "blogs/edit_post.html", context)


def check_owner_post(owner, user):
    if owner != user:
        raise Http404

blog/blogs/templates/blogs/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>BLOG!!!</title>
  </head>
  <body>
    {% block content %}{% endblock content %}
  </body>
</html>

blog/blogs/templates/blogs/edit_post.html
{% extends 'blogs/base.html' %} {% block content %}
<h3>Add a new post</h3>

<form action="{% url 'blogs:edit_post' post.id %}" method="POST">
  {% csrf_token %} {{ form.as_div}}
  <button type="submit">Edit post</button>
</form>

{% endblock content %}

blog/blogs/templates/blogs/index.html
{% extends 'blogs/base.html' %} {% block content %}
<h1>INDEX!!!!@#Q$E</h1>
{% if user.is_authenticated %}
<p>Hello, {{user.username}}</p>
<p><a href="{% url 'blogs:new_post' %}">New Post</a></p>
<form action="{% url 'accounts:logout' %}" method="post">
  {% csrf_token %}
  <button type="submit">Log out</button>
</form>
{% else %}
<a href="{% url 'accounts:register' %}">Register</a>
<a href="{% url 'accounts:login' %}">Login</a>
{% endif %}

<ul>
  {% for post in posts %}
  <li>
    <h3>{{post.title}}</h3>
    <p>{{ post.date_added|date:'M d, Y g:i A' }}</p>
    <p>{{ post.text|linebreaks }}</p>
    <a href="{% url 'blogs:edit_post' post.id %}">Edit post</a>
  </li>
  {% empty %}
  <li>No posts here.</li>
  {% endfor %}
</ul>
{% endblock content %}

blog/blogs/templates/blogs/new_post.html
{% extends 'blogs/base.html' %} {% block content %}
<h3>Add a new post</h3>

<form action="{% url 'blogs:new_post' %}" method="POST">
  {% csrf_token %} {{ form.as_div}}
  <button type="submit">Add post</button>
</form>

{% endblock content %}